### ISSUE TITLE
missing pysteamcmdwrapper

### ISSUE THREAD

**Issue by odyn666** [venraij/GameServerManager#1]
after launching error occurs :

Traceback (most recent call last):
  File "main.py", line 11, in <module>
    from initialSetup import setupTool
  File "/home/steam/GameServerManager-0.03/initialSetup.py", line 2, in <module>
    from checkSteamCmd import setupSteamCmd
  File "/home/steam/GameServerManager-0.03/checkSteamCmd.py", line 2, in <module>
    from pysteamcmdwrapper import SteamCMD
ModuleNotFoundError: No module named 'pysteamcmdwrapper'

**Comment by venraij** [comment]
I'm actually working on a full rewrite in Go which will make it work natively on Linux, MacOS and Windows. It will use https://github.com/venraij/go-chocolatey and https://github.com/venraij/go-steamcmd

SteamCMD works which is the most important part working to get started. Next up will be getting the game servers that were present in the python version.
